---

- hosts: web
  become: true
  tasks: 

  - name: remove httpd
    yum:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"

  - name: remove php support
    yum: 
      name: php
      state: absent
    when: ansible_distribution == "CentOS"
